function avgError = measureError(original3DPoints, reconstructed3DPoints)
    euclideanDistances = zeros(12, 1);
    for i=1:12
        oPoint = [original3DPoints(1,i);...
                  original3DPoints(2,i);...
                  original3DPoints(3,i)];
        rPoint = [reconstructed3DPoints(1,i);...
                  reconstructed3DPoints(2,i);...
                  reconstructed3DPoints(3,i)];
        euclideanDistances(i) = computeEuclidean(oPoint, rPoint);
    end
    avgError = sum(euclideanDistances) / 12;
end

function distance = computeEuclidean(originalPoint, reconstructedPoint)
    distance = sqrt(((originalPoint(1)-reconstructedPoint(1)).^2) + ...
                    ((originalPoint(2)-reconstructedPoint(2)).^2) + ...
                    ((originalPoint(3)-reconstructedPoint(3)).^2));
end